### PR TITLE
Added support for image-embedding.

### PR DESCRIPTION
**Pull request by dsoprea**
Retrieve and embed images directly into the document.

If you like it, please merge and publish as soon as possible.

### CODE REVIEW

**Comment by dsoprea** [comment]
I've written twelve tests against every branching point that I've added. I've been writing/debugging tests for hours for all of the Python versions. I'd hate to be the guy who breaks the 100% coverage, but I'm not sure there's any more I can do.

This is an important and useful functionality. What do I have to do to get it merged?

**Comment by lepture** [comment]
Please add this into [mistune-contrib](https://github.com/lepture/mistune-contrib).

**Comment by dsoprea** [comment]
Okay.

**Comment by dsoprea** [comment]
Created at https://github.com/dsoprea/markdown-embedimages and upload as package "markdown-embedimages".

**Comment by lepture** [comment]
Thanks.

**Pull request closed without merging**
