### PR TITLE
Fix typo "axt" used instead of ATX

### PR DESCRIPTION
**Pull request by schorfma**
Hello,

When rendering the abstract syntax tree of headings, I found out there is a typo which names ATX headings (see <https://spec.commonmark.org/0.30/#atx-headings>) `"axt"`.

I have created a pull request containing the changes from `axt` to `atx` in any form throughout the repository.

I have not considered what to do about other projects potentially depending on the exact heading style `axt`, yet.

Greetings
Martin

### CODE REVIEW

**Comment by lepture** [comment]
Thanks, this is a MUST fix typo.

**Comment by abbasidaniyal** [comment]
Hey!

I think this fix was released recently and it has broken nbgrader which was extending the BlockParser class.
[here](https://github.com/jupyter/nbconvert/blob/6e5fdb31b77314a85f6ac199a92d4d1dc0f67f1d/nbconvert/filters/markdown_mistune.py#L69)

I think we should support the old name along with the typo fix as this is not a major version release.

Thoughts @lepture ?

**Comment by lepture** [comment]
@abbasidaniyal How could it support both names?

**Comment by abbasidaniyal** [comment]
Hey

From the top of my mind, I'd say we could have keep the method `def parse_axt_heading` which internally calls the new `def parse_atx_heading` and raised a deprecation warning informing the users about the typo fix but I think there might be some added handling that we would have to support. 

Since this was not a major release, I believe it broke a lot of dependant packages which extended the `parse_atx_heading` method, `nbconvert` being one of the major ones which inturn propogated the issue to `nbgrader` and so on...

However, it was handled in `nbconvert` so it worked for me but I believe there might be other dependant packages which might have been affected.

**Pull request merged**
