### PR TITLE
use re.finditer for inline regexes

### PR DESCRIPTION
**Pull request by jendrikseipp**
Here is the requested patch, updated for the mistune-0.8 branch.

### CODE REVIEW

**Comment by lepture** [comment]
@jendrikseipp Thanks, but the tests are failed.

**Comment by jendrikseipp** [comment]
I fixed almost all tests. The new code doesn't allow for overlapping or nested regular expressions. I'm not sure if this is a problem. This leads to one failing test case: if we have the following markdown text

```
[Something in brackets like [this][] should work]

[this]: foo
```

then the old code will match a nolink ([Something in brackets like [this][] should work]) and a reflink ([this][]). The new code will match a nolink and not look into it, but just output the whole content. So the results are:

```
old: <p>[Something in brackets like <a href="foo">this</a> should work]</p>
new: <p>[Something in brackets like [this][] should work]</p>
```

Do markdown parsers need to allow overlapping regexes, or can we somehow fix this problem? E.g., we could make sure that `[markdown links]` may not contain square brackets.

**Comment by jendrikseipp** [comment]
I have added a fix for the issue mentioned above. Tell me if you can think of a better fix.

**Comment by lepture** [comment]
@jendrikseipp I appreciate your works. I'm working on the block parsers with your solution right now. I'll accept this PR later.

**Pull request merged**
